apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/emmayusufu/nodejs-k8s-demo.git
    targetRevision: HEAD
    path: nodejs-k8s-chart
    helm:
      valueFiles:
        - values.yaml
      # parameters:
      #   - name: image.pullSecrets
      #     value: ghcr-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
