name: Node Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/nodejs-k8s-demo
          tags: |
            type=sha,format=short
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Get short SHA
        id: sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Update Helm values
        run: |
          # Update the image.tag value in values.yaml
          VERSION="${{ steps.sha.outputs.short_sha }}"
          IMAGE_REPO="ghcr.io/${{ github.repository_owner }}/nodejs-k8s-demo"

          yq e -i '.image.repository = "'"$IMAGE_REPO"'"' ./nodejs-k8s-chart/values.yaml
          yq e -i '.image.tag = "'"$VERSION"'"' ./nodejs-k8s-chart/values.yaml

      - name: Commit and push updated values file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Helm chart to version ${{ steps.sha.outputs.short_sha }}"
          file_pattern: nodejs-k8s-chart/values.yaml
